# Generated by Django 3.1.7 on 2021-05-30 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=200, verbose_name='название жанра')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='имя')),
                ('last_name', models.CharField(max_length=200, verbose_name='фамилия')),
                ('birth_date', models.DateField(verbose_name='дата рождения')),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_name', models.CharField(max_length=200, verbose_name='название фильма')),
                ('pub_date', models.DateField(verbose_name='дата выхода')),
                ('box_office', models.IntegerField(verbose_name='кассовые сборы')),
                ('actors', models.ManyToManyField(related_name='actor_id', to='app.Person')),
                ('genre', models.ManyToManyField(to='app.Genre')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.person')),
            ],
        ),
    ]
