# Generated by Django 3.1.7 on 2021-05-30 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='actors',
        ),
    ]
